on:
  push:
jobs:
  build_postgres:
    name: Build Postgres
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version: [15, 16]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx create --use
          docker buildx build -f postgres.${{ matrix.version }}.Containerfile -t ghcr.io/clanny/postgres:${{ matrix.version }} . --push
